INSERT INTO USER (LAST_NAME, FIRST_NAME, EMAIL, BIRTHDAY, NUMBER_OF_TICKETS) VALUES('Adams', 'Roy', 'radams1v@xinhuanet.com', '1985-07-18', 10);
INSERT INTO USER (LAST_NAME, FIRST_NAME, EMAIL, BIRTHDAY, NUMBER_OF_TICKETS) VALUES('Adams', 'Martin', 'madams2b@msu.edu', '1985-07-22', 2);
INSERT INTO USER (LAST_NAME, FIRST_NAME, EMAIL, BIRTHDAY, NUMBER_OF_TICKETS) VALUES('Alvarez', 'Roger', 'ralvarezk@blogs.com', '1985-07-30', 1);
INSERT INTO USER (LAST_NAME, FIRST_NAME, EMAIL, BIRTHDAY, NUMBER_OF_TICKETS) VALUES('Alvarez', 'Anne', 'aalvarez1y@mlb.com', '1985-06-18', 0);
INSERT INTO USER (LAST_NAME, FIRST_NAME, EMAIL, BIRTHDAY, NUMBER_OF_TICKETS) VALUES('Alvarez', 'Ann', 'aalvarez20@jalbum.net', '1985-07-18',0);
INSERT INTO USER (LAST_NAME, FIRST_NAME, EMAIL, BIRTHDAY, NUMBER_OF_TICKETS) VALUES('Anderson', 'Betty', 'banderson14@digg.com', '1985-10-18', 0);
INSERT INTO USER (LAST_NAME, FIRST_NAME, EMAIL, BIRTHDAY, NUMBER_OF_TICKETS) VALUES('Anderson', 'Laura', 'landerson24@icio.us', '1985-01-18', 0);
INSERT INTO USER (LAST_NAME, FIRST_NAME, EMAIL, BIRTHDAY, NUMBER_OF_TICKETS) VALUES('Armstrong', 'Christopher', 'carmstrong2p@cyberchimps.com', '1985-07-18', 0);
INSERT INTO USER (LAST_NAME, FIRST_NAME, EMAIL, BIRTHDAY, NUMBER_OF_TICKETS) VALUES('Bell', 'David', 'dbell2l@wp.com', '1985-07-18', 0);
INSERT INTO USER (LAST_NAME, FIRST_NAME, EMAIL, BIRTHDAY, NUMBER_OF_TICKETS) VALUES('Berry', 'Paula', 'pberry1z@admin.ch', '1985-07-18', 0);
INSERT INTO USER (LAST_NAME, FIRST_NAME, EMAIL, BIRTHDAY, NUMBER_OF_TICKETS) VALUES('Berry', 'Paula', 'pberry1z@163.ch', '1985-07-18', 0);
INSERT INTO USER (LAST_NAME, FIRST_NAME, EMAIL, BIRTHDAY, NUMBER_OF_TICKETS) VALUES('Berry', 'Paula', 'pberry1z@yahoo.ch', '1985-07-18', 0);

